import pytest
from appy import ticket
def test_czy_bilet_ma_tytul():
    bilet = ticket("Problem z kablem","Kabel jest dlugi","High")
    assert bilet.client_name == "Problem z kablem"
def test_kompletny_bilet():
    bilet3 = ticket("Marek","Problem z komputerem","High")
    assert bilet3.client_name == "Marek"
    assert bilet3.problem_description == "Problem z komputerem"
    assert bilet3.priority == "High"
def test_gdy_pusty():
    pusty_bilet = ticket("Igor","","Low")
    assert pusty_bilet.client_name == "Igor"
    assert pusty_bilet.problem_description == ""
    assert pusty_bilet.priority == "Low"
def test_gdy_dlugie():
    dlugi_tytul = ticket("KAKSDKSDAKSDAKSKDAKSADKSADKSDKSADKSDAKSKDAKSDAKSDAKSDAKDSAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK","Problem","High")
    assert dlugi_tytul.client_name == "KAKSDKSDAKSDAKSKDAKSADKSADKSDKSADKSDAKSKDAKSDAKSDAKSDAKDSAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
def test_zmiana_statusu():
    ticket_new = ticket("Małgorzata","Awaria plc","Low")
    assert ticket_new.status == "Open"
    
    ticket_new.resolve()
    assert ticket_new.status == "Resolved"
def test_gdy_ticket_close():
    ticket3 = ticket("Małgosia","Wirus","High")
    assert ticket3.status == "Resolved"
    